package server

import (
	_ "github.com/championswimmer/api.midpoint.place/src/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/championswimmer/api.midpoint.place/src/routes"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger"
)

// @title Midpoint Place API
// @version 1.0
// @description This is the API for the Midpoint Place project
// @host api.midpoint.place
// @BasePath /v1
// @schemes http https
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func CreateServer() *fiber.App {
	app := fiber.New(fiber.Config{
		// Prefork: true,
	})

	app.Use(logger.New(logger.Config{
		Format: "🌐 REQUEST ▶️ -------- [${ip}]:${port} ${status} - ${method} ${path}\n",
	}))

	// enable cors
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, Authorization",
	}))

	apiV1 := app.Group("/v1")

	apiV1.Route("/users", routes.UsersRoute())
	apiV1.Route("/groups", routes.GroupsRoute())
	apiV1.Route("/waitlist", routes.WaitlistRoute())

	app.Get("/docs/*", swagger.HandlerDefault)

	return app
}
